WebhookClientUrl: ''
WebhookClientUsername: ''
WebhookClientAvatarUrl: ''
EmbedTitle: ''
EmbedHexColorWhenServerIsOnline: ''
EmbedHexColorWhenServerIsOffline: ''
EmbedDescriptionWhenServerIsOnline: ''
EmbedDescriptionWhenServerIsOffline: ''